# -*- coding: utf-8 -*-
"""Fraud 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSKnpSDJ2jkDEgCUDAhvEs0JTMTyRsVu
"""

import tensorflow as tf
if tf.test.gpu_device_name():
    print("Gpu found !!!")
    !nvidia-smi
else:
  print("gpu not found")

import pandas as pd

# Install xlrd for reading .xls files if not already installed
!pip install xlrd

file_path = "/content/sample_data/PS_20174392719_1491204439457_log.xlsx"

# Load the dataset. The first row of the file appears to be a header with unusual entries
# that cause mixed type issues. Skipping it and applying standard column names.
column_names = ['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
                'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFlaggedFraud', 'isFraud']
df = pd.read_excel(file_path, header=None, names=column_names, skiprows=1)

# Ensure numeric columns are correctly typed, coercing errors to NaN
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
df['isFraud'] = pd.to_numeric(df['isFraud'], errors='coerce').astype('Int64') # Use Int64 for nullable integer
df['step'] = pd.to_numeric(df['step'], errors='coerce').astype('Int64')
df['oldbalanceOrg'] = pd.to_numeric(df['oldbalanceOrg'], errors='coerce')
df['newbalanceOrig'] = pd.to_numeric(df['newbalanceOrig'], errors='coerce')
df['oldbalanceDest'] = pd.to_numeric(df['oldbalanceDest'], errors='coerce')
df['newbalanceDest'] = pd.to_numeric(df['newbalanceDest'], errors='coerce')

print("Dataset Loaded Successfully")
print("Total Records:", len(df))
print("Total Columns:", df.shape[1])

# Diagnose the 'isFraud' column
print("\nUnique values and counts for 'isFraud' column:")
print(df['isFraud'].value_counts(dropna=False))

print("Top 5 Rows")
print(df.head())

print("\nLast 5 Rows")
print(df.tail())

print("\nDataset Info")
print(df.info())

print("\nFraud Distribution")
print(df.iloc[:, -1].value_counts())

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# The previous column renaming is no longer needed as columns are now explicitly named during load.
# Removed: df = df.rename(columns={'5192810033': 'amount', '0': 'isFraud'})

# Duplicate Check
print("Duplicate Rows:", df.duplicated().sum())

# Null Check
print("\nNull Values:")
print(df.isnull().sum())

# Outlier Detection (Amount Column)
Q1 = df['amount'].quantile(0.25)
Q3 = df['amount'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['amount'] < lower) | (df['amount'] > upper)]

print("\nTotal Outliers:", len(outliers))

# Boxplot
plt.figure(figsize=(6,4))
sns.boxplot(x=df['amount'])
plt.title("Outlier Detection - Amount Column")
plt.show()

# Keep all fraud + sample legitimate

fraud_df = df[df['isFraud'] == 1]
nonfraud_population_size = len(df[df['isFraud'] == 0])
# Sample all available non-fraudulent records as the population is small
nonfraud_df = df[df['isFraud'] == 0].sample(n=nonfraud_population_size, random_state=42)

df_sample = pd.concat([fraud_df, nonfraud_df])

print("Sample Size:", len(df_sample))

print(df_sample.columns.tolist())

df_sample['type'] = df_sample['type'].astype('category').cat.codes
df_sample['nameOrig'] = df_sample['nameOrig'].astype('category').cat.codes
df_sample['nameDest'] = df_sample['nameDest'].astype('category').cat.codes

from sklearn.preprocessing import StandardScaler

features = ['amount','oldbalanceOrg','newbalanceOrig','oldbalanceDest','newbalanceDest']
scaler = StandardScaler()

df_sample[features] = scaler.fit_transform(df_sample[features])

# Install PyTorch Geometric dependencies properly

import torch
print("Torch Version:", torch.__version__)

!pip install torch-scatter -f https://data.pyg.org/whl/torch-2.2.0+cpu.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-2.2.0+cpu.html
!pip install torch-cluster -f https://data.pyg.org/whl/torch-2.2.0+cpu.html
!pip install torch-spline-conv -f https://data.pyg.org/whl/torch-2.2.0+cpu.html
!pip install torch-geometric

import pandas as pd
import numpy as np
import torch

# Define column names for the Excel file
column_names = ['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
                'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFlaggedFraud', 'isFraud']

# Load dataset
file_path = "/content/sample_data/PS_20174392719_1491204439457_log.xlsx" # Corrected file path and extension
df = pd.read_excel(file_path, header=None, names=column_names, skiprows=1) # Use pd.read_excel with correct parameters

# Ensure numeric columns are correctly typed, coercing errors to NaN
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
df['isFraud'] = pd.to_numeric(df['isFraud'], errors='coerce').astype('Int64') # Use Int64 for nullable integer
df['step'] = pd.to_numeric(df['step'], errors='coerce').astype('Int64')
df['oldbalanceOrg'] = pd.to_numeric(df['oldbalanceOrg'], errors='coerce')
df['newbalanceOrig'] = pd.to_numeric(df['newbalanceOrig'], errors='coerce')
df['oldbalanceDest'] = pd.to_numeric(df['oldbalanceDest'], errors='coerce')
df['newbalanceDest'] = pd.to_numeric(df['newbalanceDest'], errors='coerce')

print("Original Dataset Shape:", df.shape)

# Sampling (creates df_sample)
fraud_df = df[df['isFraud'] == 1]
nonfraud_population_size = len(df[df['isFraud'] == 0])
# Sample all available non-fraudulent records as the population is small
nonfraud_df = df[df['isFraud'] == 0].sample(n=nonfraud_population_size, random_state=42)

df_sample = pd.concat([fraud_df, nonfraud_df])

print("Sample Created Successfully:", df_sample.shape)

# Define Features
features = ['amount','oldbalanceOrg','newbalanceOrig','oldbalanceDest','newbalanceDest']

# Scale Features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_sample[features] = scaler.fit_transform(df_sample[features])

print("Preprocessing Completed Successfully")

from torch_geometric.data import Data

x = torch.tensor(df_sample[features].values, dtype=torch.float)
y = torch.tensor(df_sample['isFraud'].values, dtype=torch.long)

print("Tensor Shapes:", x.shape, y.shape)

from sklearn.model_selection import train_test_split
import numpy as np
import torch

# Create indices
indices = np.arange(len(df_sample))

# Split
train_idx, test_idx = train_test_split(
    indices,
    test_size=0.3,
    random_state=42,
    stratify=df_sample['isFraud']  # maintains fraud ratio
)

# Create masks
train_mask = torch.zeros(len(df_sample), dtype=torch.bool)
test_mask = torch.zeros(len(df_sample), dtype=torch.bool)

train_mask[train_idx] = True
test_mask[test_idx] = True

from torch_geometric.data import Data
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

# Simple sequential edge connection (demo purpose)
edge_index = []
for i in range(len(df_sample)-1):
    edge_index.append([i, i+1])

edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous()

# Create graph data object
data = Data(x=x, edge_index=edge_index, y=y)
data.train_mask = train_mask
data.test_mask = test_mask

print("Graph Created Successfully")
print(data)

class GCN(torch.nn.Module):
    def __init__(self):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(data.num_features, 32)
        self.conv2 = GCNConv(32, 2)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = F.relu(self.conv1(x, edge_index))
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

model = GCN()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

print("Model Initialized Successfully")

class GCN(torch.nn.Module):
    def __init__(self):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(data.num_features, 32)
        self.conv2 = GCNConv(32, 2)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = F.relu(self.conv1(x, edge_index))
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

model = GCN()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

print("Model Initialized Successfully")

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import seaborn as sns
import matplotlib.pyplot as plt

model.eval()
pred = model(data).argmax(dim=1)

y_true = data.y[data.test_mask].numpy()
y_pred = pred[data.test_mask].numpy()

# Metrics
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print("\nAccuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Non-Fraud','Fraud'],
            yticklabels=['Non-Fraud','Fraud'])
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Metrics Bar Graph
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
values = [accuracy, precision, recall, f1]

plt.figure(figsize=(7,5))
bars = plt.bar(metrics, values, color=['blue','green','orange','red'])
plt.ylim(0,1)
plt.title("Model Performance Metrics")

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01,
             round(yval,3), ha='center')

plt.show()

torch.save(model.state_dict(), "paysim_gcn_model.pth")
print("Model Saved Successfully")